# Generated by Django 5.2.13 on 2026-04-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_city_order_house_number_order_pincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
