# Generated by Django 5.2.13 on 2026-04-17 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userprofile_otp_prescription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='image_url',
        ),
        migrations.AddField(
            model_name='prescription',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/'),
        ),
        migrations.CreateModel(
            name='FraudRiskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('risk_level', models.CharField(default='low', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('context', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
