# Generated by Django 5.2.13 on 2026-04-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_prescription_image_url_prescription_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='bank_account_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='shop',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='shop',
            name='gst_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='shop',
            name='ifsc_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_kyc_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='pan_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
