# Generated by Django 5.2.13 on 2026-04-19 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_order_payment_reference_order_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, default='mock_gateway', max_length=40)),
                ('event_name', models.CharField(blank=True, default='', max_length=100)),
                ('event_id', models.CharField(blank=True, default='', max_length=120)),
                ('idempotency_key', models.CharField(max_length=140, unique=True)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=120)),
                ('gateway_payment_id', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(blank=True, default='', max_length=40)),
                ('raw_payload', models.TextField(blank=True, default='')),
                ('signature_valid', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('replay_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='api.paymenttransaction')),
            ],
        ),
    ]
