# Generated by Django 5.2.13 on 2026-04-19 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_paymentwebhookevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeout_minutes', models.IntegerField(default=30)),
                ('limit', models.IntegerField(default=200)),
                ('status_filter', models.CharField(blank=True, default='', max_length=20)),
                ('provider_filter', models.CharField(blank=True, default='', max_length=40)),
                ('payment_method_filter', models.CharField(blank=True, default='', max_length=20)),
                ('summary_json', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
