# Generated by Django 5.2.13 on 2026-04-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_paymentreconciliationrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='email_address',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]