# Generated by Django 5.2.13 on 2026-04-19 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_email_verification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_mobile_verified',
        ),
    ]
