// Generated by delombok at Sun May 17 19:44:51 IST 2026
package com.medifind.pharmaxpress.model;

import jakarta.persistence.*;

@Entity
@Table(uniqueConstraints = @UniqueConstraint(columnNames = {"user_id", "medicine_id"}))
public class CartItem extends TimestampedEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(optional = false)
    private UserAccount user;
    @ManyToOne(optional = false)
    private Medicine medicine;
    private Integer quantity;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static Integer $default$quantity() {
        return 1;
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class CartItemBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UserAccount user;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Medicine medicine;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean quantity$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Integer quantity$value;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        CartItemBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CartItem.CartItemBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CartItem.CartItemBuilder user(final UserAccount user) {
            this.user = user;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CartItem.CartItemBuilder medicine(final Medicine medicine) {
            this.medicine = medicine;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CartItem.CartItemBuilder quantity(final Integer quantity) {
            this.quantity$value = quantity;
            quantity$set = true;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public CartItem build() {
            Integer quantity$value = this.quantity$value;
            if (!this.quantity$set) quantity$value = CartItem.$default$quantity();
            return new CartItem(this.id, this.user, this.medicine, quantity$value);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "CartItem.CartItemBuilder(id=" + this.id + ", user=" + this.user + ", medicine=" + this.medicine + ", quantity$value=" + this.quantity$value + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static CartItem.CartItemBuilder builder() {
        return new CartItem.CartItemBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UserAccount getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Medicine getMedicine() {
        return this.medicine;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getQuantity() {
        return this.quantity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUser(final UserAccount user) {
        this.user = user;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMedicine(final Medicine medicine) {
        this.medicine = medicine;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setQuantity(final Integer quantity) {
        this.quantity = quantity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public CartItem() {
        this.quantity = CartItem.$default$quantity();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public CartItem(final Long id, final UserAccount user, final Medicine medicine, final Integer quantity) {
        this.id = id;
        this.user = user;
        this.medicine = medicine;
        this.quantity = quantity;
    }
}
