// Generated by delombok at Sun May 17 19:44:51 IST 2026
package com.medifind.pharmaxpress.model;

import jakarta.persistence.*;

@Entity
public class FraudRiskEvent extends TimestampedEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(optional = false)
    private UserAccount user;
    @Column(nullable = false, length = 80)
    private String action;
    private String riskLevel;
    @Column(columnDefinition = "CLOB")
    private String reason;
    @Column(columnDefinition = "CLOB")
    private String context;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$riskLevel() {
        return "low";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$reason() {
        return "";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$context() {
        return "";
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class FraudRiskEventBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UserAccount user;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String action;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean riskLevel$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String riskLevel$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean reason$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String reason$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean context$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String context$value;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        FraudRiskEventBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public FraudRiskEvent.FraudRiskEventBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public FraudRiskEvent.FraudRiskEventBuilder user(final UserAccount user) {
            this.user = user;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public FraudRiskEvent.FraudRiskEventBuilder action(final String action) {
            this.action = action;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public FraudRiskEvent.FraudRiskEventBuilder riskLevel(final String riskLevel) {
            this.riskLevel$value = riskLevel;
            riskLevel$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public FraudRiskEvent.FraudRiskEventBuilder reason(final String reason) {
            this.reason$value = reason;
            reason$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public FraudRiskEvent.FraudRiskEventBuilder context(final String context) {
            this.context$value = context;
            context$set = true;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public FraudRiskEvent build() {
            String riskLevel$value = this.riskLevel$value;
            if (!this.riskLevel$set) riskLevel$value = FraudRiskEvent.$default$riskLevel();
            String reason$value = this.reason$value;
            if (!this.reason$set) reason$value = FraudRiskEvent.$default$reason();
            String context$value = this.context$value;
            if (!this.context$set) context$value = FraudRiskEvent.$default$context();
            return new FraudRiskEvent(this.id, this.user, this.action, riskLevel$value, reason$value, context$value);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "FraudRiskEvent.FraudRiskEventBuilder(id=" + this.id + ", user=" + this.user + ", action=" + this.action + ", riskLevel$value=" + this.riskLevel$value + ", reason$value=" + this.reason$value + ", context$value=" + this.context$value + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static FraudRiskEvent.FraudRiskEventBuilder builder() {
        return new FraudRiskEvent.FraudRiskEventBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UserAccount getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getAction() {
        return this.action;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getRiskLevel() {
        return this.riskLevel;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getReason() {
        return this.reason;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getContext() {
        return this.context;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUser(final UserAccount user) {
        this.user = user;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAction(final String action) {
        this.action = action;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRiskLevel(final String riskLevel) {
        this.riskLevel = riskLevel;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setReason(final String reason) {
        this.reason = reason;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setContext(final String context) {
        this.context = context;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public FraudRiskEvent() {
        this.riskLevel = FraudRiskEvent.$default$riskLevel();
        this.reason = FraudRiskEvent.$default$reason();
        this.context = FraudRiskEvent.$default$context();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public FraudRiskEvent(final Long id, final UserAccount user, final String action, final String riskLevel, final String reason, final String context) {
        this.id = id;
        this.user = user;
        this.action = action;
        this.riskLevel = riskLevel;
        this.reason = reason;
        this.context = context;
    }
}
