// Generated by delombok at Sun May 17 19:44:51 IST 2026
package com.medifind.pharmaxpress.model;

import jakarta.persistence.*;

@Entity
public class Medicine extends TimestampedEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(optional = false)
    private Shop shop;
    @Column(nullable = false, length = 100)
    private String name;
    private String brand;
    private String category;
    @Column(columnDefinition = "CLOB")
    private String description;
    private String composition;
    private boolean prescriptionRequired;
    @Column(nullable = false)
    private Double price;
    private boolean inStock;
    private Integer stockQuantity = 0;
    private String batchNumber = "";
    private String manufacturer = "";
    private String expiryDate = "";
    private String imageUrl = "";

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$brand() {
        return "";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$category() {
        return "General";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$description() {
        return "";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$composition() {
        return "";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static boolean $default$prescriptionRequired() {
        return false;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static boolean $default$inStock() {
        return true;
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class MedicineBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Shop shop;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String name;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean brand$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String brand$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean category$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String category$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean description$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String description$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean composition$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String composition$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean prescriptionRequired$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean prescriptionRequired$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Double price;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean inStock$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean inStock$value;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        MedicineBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Medicine.MedicineBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Medicine.MedicineBuilder shop(final Shop shop) {
            this.shop = shop;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Medicine.MedicineBuilder name(final String name) {
            this.name = name;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Medicine.MedicineBuilder brand(final String brand) {
            this.brand$value = brand;
            brand$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Medicine.MedicineBuilder category(final String category) {
            this.category$value = category;
            category$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Medicine.MedicineBuilder description(final String description) {
            this.description$value = description;
            description$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Medicine.MedicineBuilder composition(final String composition) {
            this.composition$value = composition;
            composition$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Medicine.MedicineBuilder prescriptionRequired(final boolean prescriptionRequired) {
            this.prescriptionRequired$value = prescriptionRequired;
            prescriptionRequired$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Medicine.MedicineBuilder price(final Double price) {
            this.price = price;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Medicine.MedicineBuilder inStock(final boolean inStock) {
            this.inStock$value = inStock;
            inStock$set = true;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Medicine build() {
            String brand$value = this.brand$value;
            if (!this.brand$set) brand$value = Medicine.$default$brand();
            String category$value = this.category$value;
            if (!this.category$set) category$value = Medicine.$default$category();
            String description$value = this.description$value;
            if (!this.description$set) description$value = Medicine.$default$description();
            String composition$value = this.composition$value;
            if (!this.composition$set) composition$value = Medicine.$default$composition();
            boolean prescriptionRequired$value = this.prescriptionRequired$value;
            if (!this.prescriptionRequired$set) prescriptionRequired$value = Medicine.$default$prescriptionRequired();
            boolean inStock$value = this.inStock$value;
            if (!this.inStock$set) inStock$value = Medicine.$default$inStock();
            return new Medicine(this.id, this.shop, this.name, brand$value, category$value, description$value, composition$value, prescriptionRequired$value, this.price, inStock$value);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "Medicine.MedicineBuilder(id=" + this.id + ", shop=" + this.shop + ", name=" + this.name + ", brand$value=" + this.brand$value + ", category$value=" + this.category$value + ", description$value=" + this.description$value + ", composition$value=" + this.composition$value + ", prescriptionRequired$value=" + this.prescriptionRequired$value + ", price=" + this.price + ", inStock$value=" + this.inStock$value + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static Medicine.MedicineBuilder builder() {
        return new Medicine.MedicineBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Shop getShop() {
        return this.shop;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getBrand() {
        return this.brand;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCategory() {
        return this.category;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getComposition() {
        return this.composition;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean isPrescriptionRequired() {
        return this.prescriptionRequired;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Double getPrice() {
        return this.price;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean isInStock() {
        return this.inStock;
    }

    public Integer getStockQuantity() {
        return this.stockQuantity;
    }

    public String getBatchNumber() {
        return this.batchNumber;
    }

    public String getManufacturer() {
        return this.manufacturer;
    }

    public String getExpiryDate() {
        return this.expiryDate;
    }

    public String getImageUrl() {
        return this.imageUrl;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setShop(final Shop shop) {
        this.shop = shop;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBrand(final String brand) {
        this.brand = brand;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCategory(final String category) {
        this.category = category;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setComposition(final String composition) {
        this.composition = composition;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPrescriptionRequired(final boolean prescriptionRequired) {
        this.prescriptionRequired = prescriptionRequired;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPrice(final Double price) {
        this.price = price;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setInStock(final boolean inStock) {
        this.inStock = inStock;
    }

    public void setStockQuantity(final Integer stockQuantity) {
        this.stockQuantity = stockQuantity;
    }

    public void setBatchNumber(final String batchNumber) {
        this.batchNumber = batchNumber;
    }

    public void setManufacturer(final String manufacturer) {
        this.manufacturer = manufacturer;
    }

    public void setExpiryDate(final String expiryDate) {
        this.expiryDate = expiryDate;
    }

    public void setImageUrl(final String imageUrl) {
        this.imageUrl = imageUrl;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Medicine() {
        this.brand = Medicine.$default$brand();
        this.category = Medicine.$default$category();
        this.description = Medicine.$default$description();
        this.composition = Medicine.$default$composition();
        this.prescriptionRequired = Medicine.$default$prescriptionRequired();
        this.inStock = Medicine.$default$inStock();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Medicine(final Long id, final Shop shop, final String name, final String brand, final String category, final String description, final String composition, final boolean prescriptionRequired, final Double price, final boolean inStock) {
        this.id = id;
        this.shop = shop;
        this.name = name;
        this.brand = brand;
        this.category = category;
        this.description = description;
        this.composition = composition;
        this.prescriptionRequired = prescriptionRequired;
        this.price = price;
        this.inStock = inStock;
    }
}
