// Generated by delombok at Sun May 17 19:44:51 IST 2026
package com.medifind.pharmaxpress.model;

import jakarta.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "orders")
public class Order extends TimestampedEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(optional = false)
    private UserAccount user;
    @Enumerated(EnumType.STRING)
    private OrderStatus status;
    private String paymentMethod;
    private String paymentStatus;
    private String paymentReference;
    private Double deliveryFee;
    private Double taxAmount;
    private Double discountAmount;
    private Double totalAmount;
    private String couponCode;
    private String trackingId;
    @Column(columnDefinition = "CLOB")
    private String deliveryAddress;
    private String mobileNumber;
    private String houseNumber;
    private String street;
    private String city;
    private String state;
    private String pincode;
    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<OrderItem> items;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static OrderStatus $default$status() {
        return OrderStatus.PLACED;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$paymentMethod() {
        return "cod";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$paymentStatus() {
        return "pending";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$paymentReference() {
        return "";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static Double $default$deliveryFee() {
        return 0.0;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static Double $default$taxAmount() {
        return 0.0;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static Double $default$discountAmount() {
        return 0.0;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static Double $default$totalAmount() {
        return 0.0;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$couponCode() {
        return "";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$trackingId() {
        return "";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$deliveryAddress() {
        return "";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$mobileNumber() {
        return "";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$houseNumber() {
        return "";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$street() {
        return "";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$city() {
        return "";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$state() {
        return "";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$pincode() {
        return "";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static List<OrderItem> $default$items() {
        return new ArrayList<>();
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class OrderBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UserAccount user;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean status$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private OrderStatus status$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean paymentMethod$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String paymentMethod$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean paymentStatus$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String paymentStatus$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean paymentReference$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String paymentReference$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean deliveryFee$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Double deliveryFee$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean taxAmount$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Double taxAmount$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean discountAmount$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Double discountAmount$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean totalAmount$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Double totalAmount$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean couponCode$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String couponCode$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean trackingId$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String trackingId$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean deliveryAddress$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String deliveryAddress$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean mobileNumber$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String mobileNumber$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean houseNumber$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String houseNumber$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean street$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String street$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean city$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String city$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean state$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String state$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean pincode$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String pincode$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean items$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private List<OrderItem> items$value;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        OrderBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Order.OrderBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Order.OrderBuilder user(final UserAccount user) {
            this.user = user;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Order.OrderBuilder status(final OrderStatus status) {
            this.status$value = status;
            status$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Order.OrderBuilder paymentMethod(final String paymentMethod) {
            this.paymentMethod$value = paymentMethod;
            paymentMethod$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Order.OrderBuilder paymentStatus(final String paymentStatus) {
            this.paymentStatus$value = paymentStatus;
            paymentStatus$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Order.OrderBuilder paymentReference(final String paymentReference) {
            this.paymentReference$value = paymentReference;
            paymentReference$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Order.OrderBuilder deliveryFee(final Double deliveryFee) {
            this.deliveryFee$value = deliveryFee;
            deliveryFee$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Order.OrderBuilder taxAmount(final Double taxAmount) {
            this.taxAmount$value = taxAmount;
            taxAmount$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Order.OrderBuilder discountAmount(final Double discountAmount) {
            this.discountAmount$value = discountAmount;
            discountAmount$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Order.OrderBuilder totalAmount(final Double totalAmount) {
            this.totalAmount$value = totalAmount;
            totalAmount$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Order.OrderBuilder couponCode(final String couponCode) {
            this.couponCode$value = couponCode;
            couponCode$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Order.OrderBuilder trackingId(final String trackingId) {
            this.trackingId$value = trackingId;
            trackingId$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Order.OrderBuilder deliveryAddress(final String deliveryAddress) {
            this.deliveryAddress$value = deliveryAddress;
            deliveryAddress$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Order.OrderBuilder mobileNumber(final String mobileNumber) {
            this.mobileNumber$value = mobileNumber;
            mobileNumber$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Order.OrderBuilder houseNumber(final String houseNumber) {
            this.houseNumber$value = houseNumber;
            houseNumber$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Order.OrderBuilder street(final String street) {
            this.street$value = street;
            street$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Order.OrderBuilder city(final String city) {
            this.city$value = city;
            city$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Order.OrderBuilder state(final String state) {
            this.state$value = state;
            state$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Order.OrderBuilder pincode(final String pincode) {
            this.pincode$value = pincode;
            pincode$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Order.OrderBuilder items(final List<OrderItem> items) {
            this.items$value = items;
            items$set = true;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Order build() {
            OrderStatus status$value = this.status$value;
            if (!this.status$set) status$value = Order.$default$status();
            String paymentMethod$value = this.paymentMethod$value;
            if (!this.paymentMethod$set) paymentMethod$value = Order.$default$paymentMethod();
            String paymentStatus$value = this.paymentStatus$value;
            if (!this.paymentStatus$set) paymentStatus$value = Order.$default$paymentStatus();
            String paymentReference$value = this.paymentReference$value;
            if (!this.paymentReference$set) paymentReference$value = Order.$default$paymentReference();
            Double deliveryFee$value = this.deliveryFee$value;
            if (!this.deliveryFee$set) deliveryFee$value = Order.$default$deliveryFee();
            Double taxAmount$value = this.taxAmount$value;
            if (!this.taxAmount$set) taxAmount$value = Order.$default$taxAmount();
            Double discountAmount$value = this.discountAmount$value;
            if (!this.discountAmount$set) discountAmount$value = Order.$default$discountAmount();
            Double totalAmount$value = this.totalAmount$value;
            if (!this.totalAmount$set) totalAmount$value = Order.$default$totalAmount();
            String couponCode$value = this.couponCode$value;
            if (!this.couponCode$set) couponCode$value = Order.$default$couponCode();
            String trackingId$value = this.trackingId$value;
            if (!this.trackingId$set) trackingId$value = Order.$default$trackingId();
            String deliveryAddress$value = this.deliveryAddress$value;
            if (!this.deliveryAddress$set) deliveryAddress$value = Order.$default$deliveryAddress();
            String mobileNumber$value = this.mobileNumber$value;
            if (!this.mobileNumber$set) mobileNumber$value = Order.$default$mobileNumber();
            String houseNumber$value = this.houseNumber$value;
            if (!this.houseNumber$set) houseNumber$value = Order.$default$houseNumber();
            String street$value = this.street$value;
            if (!this.street$set) street$value = Order.$default$street();
            String city$value = this.city$value;
            if (!this.city$set) city$value = Order.$default$city();
            String state$value = this.state$value;
            if (!this.state$set) state$value = Order.$default$state();
            String pincode$value = this.pincode$value;
            if (!this.pincode$set) pincode$value = Order.$default$pincode();
            List<OrderItem> items$value = this.items$value;
            if (!this.items$set) items$value = Order.$default$items();
            return new Order(this.id, this.user, status$value, paymentMethod$value, paymentStatus$value, paymentReference$value, deliveryFee$value, taxAmount$value, discountAmount$value, totalAmount$value, couponCode$value, trackingId$value, deliveryAddress$value, mobileNumber$value, houseNumber$value, street$value, city$value, state$value, pincode$value, items$value);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "Order.OrderBuilder(id=" + this.id + ", user=" + this.user + ", status$value=" + this.status$value + ", paymentMethod$value=" + this.paymentMethod$value + ", paymentStatus$value=" + this.paymentStatus$value + ", paymentReference$value=" + this.paymentReference$value + ", deliveryFee$value=" + this.deliveryFee$value + ", taxAmount$value=" + this.taxAmount$value + ", discountAmount$value=" + this.discountAmount$value + ", totalAmount$value=" + this.totalAmount$value + ", couponCode$value=" + this.couponCode$value + ", trackingId$value=" + this.trackingId$value + ", deliveryAddress$value=" + this.deliveryAddress$value + ", mobileNumber$value=" + this.mobileNumber$value + ", houseNumber$value=" + this.houseNumber$value + ", street$value=" + this.street$value + ", city$value=" + this.city$value + ", state$value=" + this.state$value + ", pincode$value=" + this.pincode$value + ", items$value=" + this.items$value + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static Order.OrderBuilder builder() {
        return new Order.OrderBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UserAccount getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public OrderStatus getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPaymentMethod() {
        return this.paymentMethod;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPaymentStatus() {
        return this.paymentStatus;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPaymentReference() {
        return this.paymentReference;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Double getDeliveryFee() {
        return this.deliveryFee;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Double getTaxAmount() {
        return this.taxAmount;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Double getDiscountAmount() {
        return this.discountAmount;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Double getTotalAmount() {
        return this.totalAmount;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCouponCode() {
        return this.couponCode;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTrackingId() {
        return this.trackingId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDeliveryAddress() {
        return this.deliveryAddress;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getMobileNumber() {
        return this.mobileNumber;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getHouseNumber() {
        return this.houseNumber;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStreet() {
        return this.street;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCity() {
        return this.city;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getState() {
        return this.state;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPincode() {
        return this.pincode;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<OrderItem> getItems() {
        return this.items;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUser(final UserAccount user) {
        this.user = user;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final OrderStatus status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPaymentMethod(final String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPaymentStatus(final String paymentStatus) {
        this.paymentStatus = paymentStatus;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPaymentReference(final String paymentReference) {
        this.paymentReference = paymentReference;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDeliveryFee(final Double deliveryFee) {
        this.deliveryFee = deliveryFee;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTaxAmount(final Double taxAmount) {
        this.taxAmount = taxAmount;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDiscountAmount(final Double discountAmount) {
        this.discountAmount = discountAmount;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTotalAmount(final Double totalAmount) {
        this.totalAmount = totalAmount;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCouponCode(final String couponCode) {
        this.couponCode = couponCode;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTrackingId(final String trackingId) {
        this.trackingId = trackingId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDeliveryAddress(final String deliveryAddress) {
        this.deliveryAddress = deliveryAddress;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMobileNumber(final String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setHouseNumber(final String houseNumber) {
        this.houseNumber = houseNumber;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStreet(final String street) {
        this.street = street;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCity(final String city) {
        this.city = city;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setState(final String state) {
        this.state = state;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPincode(final String pincode) {
        this.pincode = pincode;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setItems(final List<OrderItem> items) {
        this.items = items;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Order() {
        this.status = Order.$default$status();
        this.paymentMethod = Order.$default$paymentMethod();
        this.paymentStatus = Order.$default$paymentStatus();
        this.paymentReference = Order.$default$paymentReference();
        this.deliveryFee = Order.$default$deliveryFee();
        this.taxAmount = Order.$default$taxAmount();
        this.discountAmount = Order.$default$discountAmount();
        this.totalAmount = Order.$default$totalAmount();
        this.couponCode = Order.$default$couponCode();
        this.trackingId = Order.$default$trackingId();
        this.deliveryAddress = Order.$default$deliveryAddress();
        this.mobileNumber = Order.$default$mobileNumber();
        this.houseNumber = Order.$default$houseNumber();
        this.street = Order.$default$street();
        this.city = Order.$default$city();
        this.state = Order.$default$state();
        this.pincode = Order.$default$pincode();
        this.items = Order.$default$items();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Order(final Long id, final UserAccount user, final OrderStatus status, final String paymentMethod, final String paymentStatus, final String paymentReference, final Double deliveryFee, final Double taxAmount, final Double discountAmount, final Double totalAmount, final String couponCode, final String trackingId, final String deliveryAddress, final String mobileNumber, final String houseNumber, final String street, final String city, final String state, final String pincode, final List<OrderItem> items) {
        this.id = id;
        this.user = user;
        this.status = status;
        this.paymentMethod = paymentMethod;
        this.paymentStatus = paymentStatus;
        this.paymentReference = paymentReference;
        this.deliveryFee = deliveryFee;
        this.taxAmount = taxAmount;
        this.discountAmount = discountAmount;
        this.totalAmount = totalAmount;
        this.couponCode = couponCode;
        this.trackingId = trackingId;
        this.deliveryAddress = deliveryAddress;
        this.mobileNumber = mobileNumber;
        this.houseNumber = houseNumber;
        this.street = street;
        this.city = city;
        this.state = state;
        this.pincode = pincode;
        this.items = items;
    }
}
