// Generated by delombok at Sun May 17 19:44:51 IST 2026
package com.medifind.pharmaxpress.model;

import jakarta.persistence.*;

@Entity
public class PaymentTransaction extends TimestampedEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(optional = false)
    private UserAccount user;
    @ManyToOne
    private Order order;
    private String provider;
    private String paymentMethod;
    private Double amount;
    private String currency;
    @Enumerated(EnumType.STRING)
    private PaymentStatus status;
    private String gatewayOrderId;
    private String gatewayPaymentId;
    private String clientToken;
    @Column(columnDefinition = "CLOB")
    private String errorMessage;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public UserAccount getUser() {
        return user;
    }

    public void setUser(UserAccount user) {
        this.user = user;
    }

    public Order getOrder() {
        return order;
    }

    public void setOrder(Order order) {
        this.order = order;
    }

    public String getProvider() {
        return provider;
    }

    public void setProvider(String provider) {
        this.provider = provider;
    }

    public String getPaymentMethod() {
        return paymentMethod;
    }

    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public PaymentStatus getStatus() {
        return status;
    }

    public void setStatus(PaymentStatus status) {
        this.status = status;
    }

    public String getGatewayOrderId() {
        return gatewayOrderId;
    }

    public void setGatewayOrderId(String gatewayOrderId) {
        this.gatewayOrderId = gatewayOrderId;
    }

    public String getGatewayPaymentId() {
        return gatewayPaymentId;
    }

    public void setGatewayPaymentId(String gatewayPaymentId) {
        this.gatewayPaymentId = gatewayPaymentId;
    }

    public String getClientToken() {
        return clientToken;
    }

    public void setClientToken(String clientToken) {
        this.clientToken = clientToken;
    }

    public String getErrorMessage() {
        return errorMessage;
    }

    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$provider() {
        return "mock_gateway";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$paymentMethod() {
        return "cod";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static Double $default$amount() {
        return 0.0;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$currency() {
        return "INR";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static PaymentStatus $default$status() {
        return PaymentStatus.INITIATED;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$gatewayOrderId() {
        return "";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$gatewayPaymentId() {
        return "";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$clientToken() {
        return "";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$errorMessage() {
        return "";
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class PaymentTransactionBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UserAccount user;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Order order;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean provider$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String provider$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean paymentMethod$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String paymentMethod$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean amount$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Double amount$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean currency$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String currency$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean status$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private PaymentStatus status$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean gatewayOrderId$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String gatewayOrderId$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean gatewayPaymentId$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String gatewayPaymentId$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean clientToken$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String clientToken$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean errorMessage$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String errorMessage$value;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        PaymentTransactionBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PaymentTransaction.PaymentTransactionBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PaymentTransaction.PaymentTransactionBuilder user(final UserAccount user) {
            this.user = user;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PaymentTransaction.PaymentTransactionBuilder order(final Order order) {
            this.order = order;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PaymentTransaction.PaymentTransactionBuilder provider(final String provider) {
            this.provider$value = provider;
            provider$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PaymentTransaction.PaymentTransactionBuilder paymentMethod(final String paymentMethod) {
            this.paymentMethod$value = paymentMethod;
            paymentMethod$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PaymentTransaction.PaymentTransactionBuilder amount(final Double amount) {
            this.amount$value = amount;
            amount$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PaymentTransaction.PaymentTransactionBuilder currency(final String currency) {
            this.currency$value = currency;
            currency$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PaymentTransaction.PaymentTransactionBuilder status(final PaymentStatus status) {
            this.status$value = status;
            status$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PaymentTransaction.PaymentTransactionBuilder gatewayOrderId(final String gatewayOrderId) {
            this.gatewayOrderId$value = gatewayOrderId;
            gatewayOrderId$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PaymentTransaction.PaymentTransactionBuilder gatewayPaymentId(final String gatewayPaymentId) {
            this.gatewayPaymentId$value = gatewayPaymentId;
            gatewayPaymentId$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PaymentTransaction.PaymentTransactionBuilder clientToken(final String clientToken) {
            this.clientToken$value = clientToken;
            clientToken$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PaymentTransaction.PaymentTransactionBuilder errorMessage(final String errorMessage) {
            this.errorMessage$value = errorMessage;
            errorMessage$set = true;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PaymentTransaction build() {
            String provider$value = this.provider$value;
            if (!this.provider$set) provider$value = PaymentTransaction.$default$provider();
            String paymentMethod$value = this.paymentMethod$value;
            if (!this.paymentMethod$set) paymentMethod$value = PaymentTransaction.$default$paymentMethod();
            Double amount$value = this.amount$value;
            if (!this.amount$set) amount$value = PaymentTransaction.$default$amount();
            String currency$value = this.currency$value;
            if (!this.currency$set) currency$value = PaymentTransaction.$default$currency();
            PaymentStatus status$value = this.status$value;
            if (!this.status$set) status$value = PaymentTransaction.$default$status();
            String gatewayOrderId$value = this.gatewayOrderId$value;
            if (!this.gatewayOrderId$set) gatewayOrderId$value = PaymentTransaction.$default$gatewayOrderId();
            String gatewayPaymentId$value = this.gatewayPaymentId$value;
            if (!this.gatewayPaymentId$set) gatewayPaymentId$value = PaymentTransaction.$default$gatewayPaymentId();
            String clientToken$value = this.clientToken$value;
            if (!this.clientToken$set) clientToken$value = PaymentTransaction.$default$clientToken();
            String errorMessage$value = this.errorMessage$value;
            if (!this.errorMessage$set) errorMessage$value = PaymentTransaction.$default$errorMessage();
            return new PaymentTransaction(this.id, this.user, this.order, provider$value, paymentMethod$value, amount$value, currency$value, status$value, gatewayOrderId$value, gatewayPaymentId$value, clientToken$value, errorMessage$value);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "PaymentTransaction.PaymentTransactionBuilder(id=" + this.id + ", user=" + this.user + ", order=" + this.order + ", provider$value=" + this.provider$value + ", paymentMethod$value=" + this.paymentMethod$value + ", amount$value=" + this.amount$value + ", currency$value=" + this.currency$value + ", status$value=" + this.status$value + ", gatewayOrderId$value=" + this.gatewayOrderId$value + ", gatewayPaymentId$value=" + this.gatewayPaymentId$value + ", clientToken$value=" + this.clientToken$value + ", errorMessage$value=" + this.errorMessage$value + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static PaymentTransaction.PaymentTransactionBuilder builder() {
        return new PaymentTransaction.PaymentTransactionBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public PaymentTransaction() {
        this.provider = PaymentTransaction.$default$provider();
        this.paymentMethod = PaymentTransaction.$default$paymentMethod();
        this.amount = PaymentTransaction.$default$amount();
        this.currency = PaymentTransaction.$default$currency();
        this.status = PaymentTransaction.$default$status();
        this.gatewayOrderId = PaymentTransaction.$default$gatewayOrderId();
        this.gatewayPaymentId = PaymentTransaction.$default$gatewayPaymentId();
        this.clientToken = PaymentTransaction.$default$clientToken();
        this.errorMessage = PaymentTransaction.$default$errorMessage();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public PaymentTransaction(final Long id, final UserAccount user, final Order order, final String provider, final String paymentMethod, final Double amount, final String currency, final PaymentStatus status, final String gatewayOrderId, final String gatewayPaymentId, final String clientToken, final String errorMessage) {
        this.id = id;
        this.user = user;
        this.order = order;
        this.provider = provider;
        this.paymentMethod = paymentMethod;
        this.amount = amount;
        this.currency = currency;
        this.status = status;
        this.gatewayOrderId = gatewayOrderId;
        this.gatewayPaymentId = gatewayPaymentId;
        this.clientToken = clientToken;
        this.errorMessage = errorMessage;
    }
}
