// Generated by delombok at Sun May 17 19:44:51 IST 2026
package com.medifind.pharmaxpress.model;

import jakarta.persistence.*;

@Entity
public class PaymentWebhookEvent extends TimestampedEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String provider;
    private String eventName;
    private String eventId;
    @Column(nullable = false, unique = true, length = 140)
    private String idempotencyKey;
    @ManyToOne
    private PaymentTransaction payment;
    private String paymentReference;
    private String gatewayPaymentId;
    private String status;
    @Column(columnDefinition = "CLOB")
    private String rawPayload;
    private boolean signatureValid;
    private boolean processed;
    private Integer replayCount;
    @Column(columnDefinition = "CLOB")
    private String errorMessage;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$provider() {
        return "mock_gateway";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$eventName() {
        return "";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$eventId() {
        return "";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$paymentReference() {
        return "";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$gatewayPaymentId() {
        return "";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$status() {
        return "";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$rawPayload() {
        return "";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static boolean $default$signatureValid() {
        return false;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static boolean $default$processed() {
        return false;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static Integer $default$replayCount() {
        return 0;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$errorMessage() {
        return "";
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class PaymentWebhookEventBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean provider$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String provider$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean eventName$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String eventName$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean eventId$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String eventId$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String idempotencyKey;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private PaymentTransaction payment;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean paymentReference$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String paymentReference$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean gatewayPaymentId$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String gatewayPaymentId$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean status$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String status$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean rawPayload$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String rawPayload$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean signatureValid$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean signatureValid$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean processed$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean processed$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean replayCount$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Integer replayCount$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean errorMessage$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String errorMessage$value;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        PaymentWebhookEventBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PaymentWebhookEvent.PaymentWebhookEventBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PaymentWebhookEvent.PaymentWebhookEventBuilder provider(final String provider) {
            this.provider$value = provider;
            provider$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PaymentWebhookEvent.PaymentWebhookEventBuilder eventName(final String eventName) {
            this.eventName$value = eventName;
            eventName$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PaymentWebhookEvent.PaymentWebhookEventBuilder eventId(final String eventId) {
            this.eventId$value = eventId;
            eventId$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PaymentWebhookEvent.PaymentWebhookEventBuilder idempotencyKey(final String idempotencyKey) {
            this.idempotencyKey = idempotencyKey;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PaymentWebhookEvent.PaymentWebhookEventBuilder payment(final PaymentTransaction payment) {
            this.payment = payment;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PaymentWebhookEvent.PaymentWebhookEventBuilder paymentReference(final String paymentReference) {
            this.paymentReference$value = paymentReference;
            paymentReference$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PaymentWebhookEvent.PaymentWebhookEventBuilder gatewayPaymentId(final String gatewayPaymentId) {
            this.gatewayPaymentId$value = gatewayPaymentId;
            gatewayPaymentId$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PaymentWebhookEvent.PaymentWebhookEventBuilder status(final String status) {
            this.status$value = status;
            status$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PaymentWebhookEvent.PaymentWebhookEventBuilder rawPayload(final String rawPayload) {
            this.rawPayload$value = rawPayload;
            rawPayload$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PaymentWebhookEvent.PaymentWebhookEventBuilder signatureValid(final boolean signatureValid) {
            this.signatureValid$value = signatureValid;
            signatureValid$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PaymentWebhookEvent.PaymentWebhookEventBuilder processed(final boolean processed) {
            this.processed$value = processed;
            processed$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PaymentWebhookEvent.PaymentWebhookEventBuilder replayCount(final Integer replayCount) {
            this.replayCount$value = replayCount;
            replayCount$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PaymentWebhookEvent.PaymentWebhookEventBuilder errorMessage(final String errorMessage) {
            this.errorMessage$value = errorMessage;
            errorMessage$set = true;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PaymentWebhookEvent build() {
            String provider$value = this.provider$value;
            if (!this.provider$set) provider$value = PaymentWebhookEvent.$default$provider();
            String eventName$value = this.eventName$value;
            if (!this.eventName$set) eventName$value = PaymentWebhookEvent.$default$eventName();
            String eventId$value = this.eventId$value;
            if (!this.eventId$set) eventId$value = PaymentWebhookEvent.$default$eventId();
            String paymentReference$value = this.paymentReference$value;
            if (!this.paymentReference$set) paymentReference$value = PaymentWebhookEvent.$default$paymentReference();
            String gatewayPaymentId$value = this.gatewayPaymentId$value;
            if (!this.gatewayPaymentId$set) gatewayPaymentId$value = PaymentWebhookEvent.$default$gatewayPaymentId();
            String status$value = this.status$value;
            if (!this.status$set) status$value = PaymentWebhookEvent.$default$status();
            String rawPayload$value = this.rawPayload$value;
            if (!this.rawPayload$set) rawPayload$value = PaymentWebhookEvent.$default$rawPayload();
            boolean signatureValid$value = this.signatureValid$value;
            if (!this.signatureValid$set) signatureValid$value = PaymentWebhookEvent.$default$signatureValid();
            boolean processed$value = this.processed$value;
            if (!this.processed$set) processed$value = PaymentWebhookEvent.$default$processed();
            Integer replayCount$value = this.replayCount$value;
            if (!this.replayCount$set) replayCount$value = PaymentWebhookEvent.$default$replayCount();
            String errorMessage$value = this.errorMessage$value;
            if (!this.errorMessage$set) errorMessage$value = PaymentWebhookEvent.$default$errorMessage();
            return new PaymentWebhookEvent(this.id, provider$value, eventName$value, eventId$value, this.idempotencyKey, this.payment, paymentReference$value, gatewayPaymentId$value, status$value, rawPayload$value, signatureValid$value, processed$value, replayCount$value, errorMessage$value);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "PaymentWebhookEvent.PaymentWebhookEventBuilder(id=" + this.id + ", provider$value=" + this.provider$value + ", eventName$value=" + this.eventName$value + ", eventId$value=" + this.eventId$value + ", idempotencyKey=" + this.idempotencyKey + ", payment=" + this.payment + ", paymentReference$value=" + this.paymentReference$value + ", gatewayPaymentId$value=" + this.gatewayPaymentId$value + ", status$value=" + this.status$value + ", rawPayload$value=" + this.rawPayload$value + ", signatureValid$value=" + this.signatureValid$value + ", processed$value=" + this.processed$value + ", replayCount$value=" + this.replayCount$value + ", errorMessage$value=" + this.errorMessage$value + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static PaymentWebhookEvent.PaymentWebhookEventBuilder builder() {
        return new PaymentWebhookEvent.PaymentWebhookEventBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getProvider() {
        return this.provider;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEventName() {
        return this.eventName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEventId() {
        return this.eventId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getIdempotencyKey() {
        return this.idempotencyKey;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public PaymentTransaction getPayment() {
        return this.payment;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPaymentReference() {
        return this.paymentReference;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getGatewayPaymentId() {
        return this.gatewayPaymentId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getRawPayload() {
        return this.rawPayload;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean isSignatureValid() {
        return this.signatureValid;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean isProcessed() {
        return this.processed;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getReplayCount() {
        return this.replayCount;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getErrorMessage() {
        return this.errorMessage;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setProvider(final String provider) {
        this.provider = provider;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEventName(final String eventName) {
        this.eventName = eventName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEventId(final String eventId) {
        this.eventId = eventId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setIdempotencyKey(final String idempotencyKey) {
        this.idempotencyKey = idempotencyKey;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPayment(final PaymentTransaction payment) {
        this.payment = payment;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPaymentReference(final String paymentReference) {
        this.paymentReference = paymentReference;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setGatewayPaymentId(final String gatewayPaymentId) {
        this.gatewayPaymentId = gatewayPaymentId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRawPayload(final String rawPayload) {
        this.rawPayload = rawPayload;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSignatureValid(final boolean signatureValid) {
        this.signatureValid = signatureValid;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setProcessed(final boolean processed) {
        this.processed = processed;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setReplayCount(final Integer replayCount) {
        this.replayCount = replayCount;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setErrorMessage(final String errorMessage) {
        this.errorMessage = errorMessage;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public PaymentWebhookEvent() {
        this.provider = PaymentWebhookEvent.$default$provider();
        this.eventName = PaymentWebhookEvent.$default$eventName();
        this.eventId = PaymentWebhookEvent.$default$eventId();
        this.paymentReference = PaymentWebhookEvent.$default$paymentReference();
        this.gatewayPaymentId = PaymentWebhookEvent.$default$gatewayPaymentId();
        this.status = PaymentWebhookEvent.$default$status();
        this.rawPayload = PaymentWebhookEvent.$default$rawPayload();
        this.signatureValid = PaymentWebhookEvent.$default$signatureValid();
        this.processed = PaymentWebhookEvent.$default$processed();
        this.replayCount = PaymentWebhookEvent.$default$replayCount();
        this.errorMessage = PaymentWebhookEvent.$default$errorMessage();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public PaymentWebhookEvent(final Long id, final String provider, final String eventName, final String eventId, final String idempotencyKey, final PaymentTransaction payment, final String paymentReference, final String gatewayPaymentId, final String status, final String rawPayload, final boolean signatureValid, final boolean processed, final Integer replayCount, final String errorMessage) {
        this.id = id;
        this.provider = provider;
        this.eventName = eventName;
        this.eventId = eventId;
        this.idempotencyKey = idempotencyKey;
        this.payment = payment;
        this.paymentReference = paymentReference;
        this.gatewayPaymentId = gatewayPaymentId;
        this.status = status;
        this.rawPayload = rawPayload;
        this.signatureValid = signatureValid;
        this.processed = processed;
        this.replayCount = replayCount;
        this.errorMessage = errorMessage;
    }
}
