// Generated by delombok at Sun May 17 19:44:51 IST 2026
package com.medifind.pharmaxpress.model;

import jakarta.persistence.*;

@Entity
public class Prescription extends TimestampedEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(optional = false)
    private UserAccount user;
    @ManyToOne(optional = false)
    private Medicine medicine;
    private String filePath;
    @Column(columnDefinition = "CLOB")
    private String note;
    @Enumerated(EnumType.STRING)
    private PrescriptionStatus status;
    @ManyToOne
    private UserAccount reviewedBy;
    private java.time.Instant reviewedAt;
    @Column(columnDefinition = "CLOB")
    private String rejectionReason;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$filePath() {
        return "";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$note() {
        return "";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static PrescriptionStatus $default$status() {
        return PrescriptionStatus.PENDING;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$rejectionReason() {
        return "";
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class PrescriptionBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UserAccount user;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Medicine medicine;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean filePath$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String filePath$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean note$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String note$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean status$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private PrescriptionStatus status$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UserAccount reviewedBy;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private java.time.Instant reviewedAt;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean rejectionReason$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String rejectionReason$value;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        PrescriptionBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Prescription.PrescriptionBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Prescription.PrescriptionBuilder user(final UserAccount user) {
            this.user = user;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Prescription.PrescriptionBuilder medicine(final Medicine medicine) {
            this.medicine = medicine;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Prescription.PrescriptionBuilder filePath(final String filePath) {
            this.filePath$value = filePath;
            filePath$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Prescription.PrescriptionBuilder note(final String note) {
            this.note$value = note;
            note$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Prescription.PrescriptionBuilder status(final PrescriptionStatus status) {
            this.status$value = status;
            status$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Prescription.PrescriptionBuilder reviewedBy(final UserAccount reviewedBy) {
            this.reviewedBy = reviewedBy;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Prescription.PrescriptionBuilder reviewedAt(final java.time.Instant reviewedAt) {
            this.reviewedAt = reviewedAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Prescription.PrescriptionBuilder rejectionReason(final String rejectionReason) {
            this.rejectionReason$value = rejectionReason;
            rejectionReason$set = true;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Prescription build() {
            String filePath$value = this.filePath$value;
            if (!this.filePath$set) filePath$value = Prescription.$default$filePath();
            String note$value = this.note$value;
            if (!this.note$set) note$value = Prescription.$default$note();
            PrescriptionStatus status$value = this.status$value;
            if (!this.status$set) status$value = Prescription.$default$status();
            String rejectionReason$value = this.rejectionReason$value;
            if (!this.rejectionReason$set) rejectionReason$value = Prescription.$default$rejectionReason();
            return new Prescription(this.id, this.user, this.medicine, filePath$value, note$value, status$value, this.reviewedBy, this.reviewedAt, rejectionReason$value);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "Prescription.PrescriptionBuilder(id=" + this.id + ", user=" + this.user + ", medicine=" + this.medicine + ", filePath$value=" + this.filePath$value + ", note$value=" + this.note$value + ", status$value=" + this.status$value + ", reviewedBy=" + this.reviewedBy + ", reviewedAt=" + this.reviewedAt + ", rejectionReason$value=" + this.rejectionReason$value + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static Prescription.PrescriptionBuilder builder() {
        return new Prescription.PrescriptionBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UserAccount getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Medicine getMedicine() {
        return this.medicine;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getFilePath() {
        return this.filePath;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNote() {
        return this.note;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public PrescriptionStatus getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UserAccount getReviewedBy() {
        return this.reviewedBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.time.Instant getReviewedAt() {
        return this.reviewedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getRejectionReason() {
        return this.rejectionReason;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUser(final UserAccount user) {
        this.user = user;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMedicine(final Medicine medicine) {
        this.medicine = medicine;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFilePath(final String filePath) {
        this.filePath = filePath;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNote(final String note) {
        this.note = note;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final PrescriptionStatus status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setReviewedBy(final UserAccount reviewedBy) {
        this.reviewedBy = reviewedBy;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setReviewedAt(final java.time.Instant reviewedAt) {
        this.reviewedAt = reviewedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRejectionReason(final String rejectionReason) {
        this.rejectionReason = rejectionReason;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Prescription() {
        this.filePath = Prescription.$default$filePath();
        this.note = Prescription.$default$note();
        this.status = Prescription.$default$status();
        this.rejectionReason = Prescription.$default$rejectionReason();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Prescription(final Long id, final UserAccount user, final Medicine medicine, final String filePath, final String note, final PrescriptionStatus status, final UserAccount reviewedBy, final java.time.Instant reviewedAt, final String rejectionReason) {
        this.id = id;
        this.user = user;
        this.medicine = medicine;
        this.filePath = filePath;
        this.note = note;
        this.status = status;
        this.reviewedBy = reviewedBy;
        this.reviewedAt = reviewedAt;
        this.rejectionReason = rejectionReason;
    }
}
