// Generated by delombok at Sun May 17 19:44:51 IST 2026
package com.medifind.pharmaxpress.model;

import jakarta.persistence.*;
import java.time.Instant;

@Entity
public class UserProfile {
    @Id
    private Long id;
    @OneToOne(optional = false)
    @MapsId
    private UserAccount user;
    @Enumerated(EnumType.STRING)
    private UserRole role;
    private String mobileNumber;
    private boolean emailVerified;
    private boolean mobileVerified;
    private Instant createdAt;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static UserRole $default$role() {
        return UserRole.BUYER;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static String $default$mobileNumber() {
        return "";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static boolean $default$emailVerified() {
        return false;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static boolean $default$mobileVerified() {
        return false;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static Instant $default$createdAt() {
        return Instant.now();
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class UserProfileBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UserAccount user;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean role$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UserRole role$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean mobileNumber$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String mobileNumber$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean emailVerified$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean emailVerified$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean mobileVerified$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean mobileVerified$value;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean createdAt$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Instant createdAt$value;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        UserProfileBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public UserProfile.UserProfileBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public UserProfile.UserProfileBuilder user(final UserAccount user) {
            this.user = user;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public UserProfile.UserProfileBuilder role(final UserRole role) {
            this.role$value = role;
            role$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public UserProfile.UserProfileBuilder mobileNumber(final String mobileNumber) {
            this.mobileNumber$value = mobileNumber;
            mobileNumber$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public UserProfile.UserProfileBuilder emailVerified(final boolean emailVerified) {
            this.emailVerified$value = emailVerified;
            emailVerified$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public UserProfile.UserProfileBuilder mobileVerified(final boolean mobileVerified) {
            this.mobileVerified$value = mobileVerified;
            mobileVerified$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public UserProfile.UserProfileBuilder createdAt(final Instant createdAt) {
            this.createdAt$value = createdAt;
            createdAt$set = true;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public UserProfile build() {
            UserRole role$value = this.role$value;
            if (!this.role$set) role$value = UserProfile.$default$role();
            String mobileNumber$value = this.mobileNumber$value;
            if (!this.mobileNumber$set) mobileNumber$value = UserProfile.$default$mobileNumber();
            boolean emailVerified$value = this.emailVerified$value;
            if (!this.emailVerified$set) emailVerified$value = UserProfile.$default$emailVerified();
            boolean mobileVerified$value = this.mobileVerified$value;
            if (!this.mobileVerified$set) mobileVerified$value = UserProfile.$default$mobileVerified();
            Instant createdAt$value = this.createdAt$value;
            if (!this.createdAt$set) createdAt$value = UserProfile.$default$createdAt();
            return new UserProfile(this.id, this.user, role$value, mobileNumber$value, emailVerified$value, mobileVerified$value, createdAt$value);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "UserProfile.UserProfileBuilder(id=" + this.id + ", user=" + this.user + ", role$value=" + this.role$value + ", mobileNumber$value=" + this.mobileNumber$value + ", emailVerified$value=" + this.emailVerified$value + ", mobileVerified$value=" + this.mobileVerified$value + ", createdAt$value=" + this.createdAt$value + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static UserProfile.UserProfileBuilder builder() {
        return new UserProfile.UserProfileBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UserAccount getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UserRole getRole() {
        return this.role;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getMobileNumber() {
        return this.mobileNumber;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean isEmailVerified() {
        return this.emailVerified;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean isMobileVerified() {
        return this.mobileVerified;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Instant getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUser(final UserAccount user) {
        this.user = user;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRole(final UserRole role) {
        this.role = role;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMobileNumber(final String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEmailVerified(final boolean emailVerified) {
        this.emailVerified = emailVerified;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMobileVerified(final boolean mobileVerified) {
        this.mobileVerified = mobileVerified;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final Instant createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UserProfile() {
        this.role = UserProfile.$default$role();
        this.mobileNumber = UserProfile.$default$mobileNumber();
        this.emailVerified = UserProfile.$default$emailVerified();
        this.mobileVerified = UserProfile.$default$mobileVerified();
        this.createdAt = UserProfile.$default$createdAt();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UserProfile(final Long id, final UserAccount user, final UserRole role, final String mobileNumber, final boolean emailVerified, final boolean mobileVerified, final Instant createdAt) {
        this.id = id;
        this.user = user;
        this.role = role;
        this.mobileNumber = mobileNumber;
        this.emailVerified = emailVerified;
        this.mobileVerified = mobileVerified;
        this.createdAt = createdAt;
    }
}
